
// 
// This is an autogenerated header file. Do not edit this. If you need
// to change the definitions then change them in RobWorkConfig.hpp.in  
// 

#define RWS_VERSION "${ROBWORKSTUDIO_VERSION}"
#define RWS_VERSION_MAJOR ${ROBWORKSTUDIO_VERSION_MAJOR} 
#define RWS_VERSION_MINOR ${ROBWORKSTUDIO_VERSION_MINOR}
#define RWS_VERSION_PATCH ${ROBWORKSTUDIO_VERSION_PATCH}

#define RWS_REVISION "${ROBWORKSTUDIO_REVISION}"

/* #undef RWS_HAVE_SANDBOX */
/* #undef RWS_HAVE_LUA */
/* #undef RWS_USE_STATIC_LINK_PLUGINS */
/* #undef RW_STATIC_LINK_PLUGINS */
/* #undef RWS_USE_QT5 */
